version: '3.8'

services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    image: pfm-db:latest
    container_name: pfm-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    networks:
      - app-network
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
    restart: unless-stopped

  webapi:
    build:
      context: ./
      dockerfile: ./WebApi/Dockerfile
    image: pfm-webapi:latest
    container_name: pfm-webapi
    environment:  
      - ConnectionStrings__DefaultConnection=Server=database;Database=PersonalFinanceManager;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
    ports:
      - "5000:80"
      - "5001:443"
      - "5002:8081"
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: pfm-frontend
    container_name: pfm-frontend
    ports:
      - "3000:3000"  # frontend na localhost:3000
    networks:
      - app-network
    depends_on:
      - webapi


networks:
  app-network:
    driver: bridge

volumes:
  mssql_data:
  mssql_log: