version: '3.8'

services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    image: pfm-db:latest
    container_name: pfm-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
    restart: unless-stopped

  webapi:
    build:
      context: ./
      dockerfile: ./WebApi/Dockerfile
    image: pfm-webapi:latest
    container_name: pfm-webapi
    environment:  
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User Id=${APP_DB_USER};Password=${APP_DB_PASSWORD};TrustServerCertificate=True;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: pfm-frontend
    container_name: pfm-frontend
    ports:
      - "3000:3000"  # frontend na localhost:3000
    networks:
      - app-network
    depends_on:
      - webapi


networks:
  app-network:
    driver: bridge

volumes:
  mssql_data:
  mssql_log: